### ISSUE TITLE
SSL handshake fails with 2.7.9

### ISSUE THREAD

**Issue by rkhwaja** [captin411/ofxclient#11]
The SSL certificates are checked by default with python 2.7.9 according to PEP 476 and most of my ofx sites now fail this check.
Ideally I think ofxclient should try with the certificate checking and then allow the option of continuing without the check (by using the context returned from ssl._create_unverified_context()) and warning of the problem.
The behavior with 2.7.8 and before was to skip checking these certificates

**Comment by rodlogic** [comment]
I am seeing the same problem.

**Comment by captin411** [comment]
Have many of the banks left their OFX endpoints with broken HTTPS?  I have not run into this myself.

**Comment by rkhwaja** [comment]
This doesn't seem to be happening anymore
