### ISSUE TITLE
pip install does not work

### ISSUE THREAD

**Issue by balkierode** [captin411/ofxclient#14]
>> "BeautifulSoup>=3.0",
in  https://github.com/captin411/ofxclient/blob/master/setup.py#L47
BeautifulSoup is marked obsolete by pypi and replaced with beautifulsoup4. So pip install does not work. ref: https://pypi.python.org/pypi/BeautifulSoup/3.2.1

**Comment by captin411** [comment]
Hope this works now.  Version 2.0.1 is now python 3 compatible and that includes depending on beautiful soup 4 now.
