### ISSUE TITLE
Unable to download from Chase

### ISSUE THREAD

**Issue by michaelpigg** [captin411/ofxclient#17]
Chase has made a recent change that breaks ofxclient. They are now requiring that users perform a verification step through their website. The symptom is that download fails and the response is:

```
<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>15510<SEVERITY>ERROR
<MESSAGE>Please verify your identity within the next 7 days. Using your desktop computer, go to your bank<92>s website and visit the Secure Message Center for instructions.</STATUS><DTSERVER>20151203063424.779[-5:EST]<LANGUAGE>ENG<FI><ORG>B1<FID>10898</FI></SONRS></SIGNONMSGSRSV1><CREDITCARDMSGSRSV1><CCSTMTTRNRS><TRNUID>49048ca8d87a43dd8a6bac3f093984f6<STATUS><CODE>15500<SEVERITY>ERROR</STATUS><CLTCOOKIE>4</CCSTMTTRNRS></CREDITCARDMSGSRSV1></OFX>
```
The verification in the "Secure Message Center" is not triggered by the existing request. Based on my experiments, the request has to be an OFX 2.1.1 request that includes the new CLIENTUID element in order to trigger the verification step.

**Comment by serpman** [comment]
It looks like the CLIENTUID field is there but gets conditionally included.  If you go to your ofxclient.ini file and change `institution.client_args.ofx_version = 102` in your Chase config to `institution.client_args.ofx_version = 103`, it should work.  I had already triggered verification in the "Secure Message Center" by using Quicken, so I can't confirm that this change will trigger that process.  However, once that verification process is completed, I can confirm that my Chase downloads have resumed.

**Comment by michaelpigg** [comment]
@serpman Ah, thanks for pointing that out! I suspect that will fix it.

**Comment by michaelpigg** [comment]
Indeed, changing ofx_version to 103 allowed transactions to download and triggered the verification, so I'm closing the issue. Thanks @serpman!

**Comment by andrewgl504** [comment]
I had the same issue, and the fix suggested by @serpman fixed it for me as well. Thank you!
