### ISSUE TITLE
Cannot download AMEX OFX

### ISSUE THREAD

**Issue by ChromoX** [captin411/ofxclient#20]
DEBUG:root:posting data to https://online.americanexpress.com/myca/ofxdl/desktop/desktopDownload.do?request_type=nl_ofxdownload
    DEBUG:root:---- request ----
    DEBUG:root:OFXHEADER:100
    DATA:OFXSGML
    VERSION:102
    SECURITY:NONE
    ENCODING:USASCII
    CHARSET:1252
    COMPRESSION:NONE
    OLDFILEUID:NONE
    NEWFILEUID:b9ffc76190234a33875ea8f79f79829c

    <OFX>
    <SIGNONMSGSRQV1>
    <SONRQ>
    <DTCLIENT>20164867024420
    <USERID><username>
    <USERPASS><password>
    <LANGUAGE>ENG
    <FI>
    <ORG>AMEX
    <FID>3101
    </FI>
    <APPID>QWIN
    <APPVER>2200

    </SONRQ>
    </SIGNONMSGSRQV1>
    </OFX>
    DEBUG:root:---- response ----
    DEBUG:root:{'length': 0, 'reason': 'OK', 'code': 200, 'debuglevel': 0, 'version': 11, 'will_close': False, 'chunked': False, 'chunk_left': 'UNKNOWN', 'msg': <http.client.HTTPMessage object at 0x108708780>, 'status': 200, '_method': 'POST', 'fp': None, 'headers': <http.client.HTTPMessage object at 0x108708780>}
    DEBUG:root:OFXHEADER:100
    DATA:OFXSGML
    VERSION:102
    SECURITY:NONE
    ENCODING:USASCII
    CHARSET:1252
    COMPRESSION:NONE
    OLDFILEUID:NONE
    NEWFILEUID:b9ffc76154374a33875ea8f79f79829c

    <OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>Login successful</STATUS><DTSERVER>20160315234421.027[-7:MST]<LANGUAGE>ENG<FI><ORG>AMEX<FID>3101</FI><ORIGIN.ID>FMPWeb<CUSTOMER.TYPE>BCM<START.TIME>20160315234421</SONRS></SIGNONMSGSRSV1></OFX>

    authentication failed: 'NoneType' object has no attribute 'find'

**Comment by tgoetze** [comment]
I fixed this locally by first installing the python `lxml` and changing `cli.py` to parse with `lxml`:

In the file `C:\Python27\Lib\site-packages\ofxclient-2.0.1-\y2.7.egg\ofxclient\instituion.py`, I changed from:
````
ofx = BeautifulSoup(res, 'xml')
````
to
````
ofx = BeautifulSoup(res, 'lxml')
````

I also changed `AUTO_OPEN_DOWNLOADS = 0` in cli.py since I do not have an program to automatically load the downloaded file and the command line option is not present to switch it.

**Comment by ChromoX** [comment]
So the above change was pushed in the last tagged release (2.0.2). But I now get the following error even thought it appears that the login was successful.

```</OFX>
DEBUG:root:---- response ----
DEBUG:root:{'fp': None, 'status': 200, 'will_close': False, 'chunk_left': 'UNKNOWN', 'length': 0, 'strict': 0, 'reason': 'OK', 'version': 11, 'debuglevel': 0, 'msg': <httplib.HTTPMessage instance at 0x10fc8c9e0>, 'chunked': 0, '_method': u'POST'}
DEBUG:root:OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:9dd6f41ac7904b409591c198d9b922f2

<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>Login successful</STATUS><DTSERVER>20160601190228.034[-7:MST]<LANGUAGE>ENG<FI><ORG>AMEX<FID>3101</FI><ORIGIN.ID>FMPWeb<CUSTOMER.TYPE>BCM<START.TIME>20160601190228</SONRS></SIGNONMSGSRSV1></OFX>


authentication failed: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?```

**Comment by tgoetze** [comment]
Are you sure you have lxml installed? You can easily test by running a short program like the following which is doing the parsing logic from the ofxclient on the response data you posted:
````
from bs4 import BeautifulSoup

res = '''OFXHEADER:100
DATA:OFXSGML
VERSION:102
SECURITY:NONE
ENCODING:USASCII
CHARSET:1252
COMPRESSION:NONE
OLDFILEUID:NONE
NEWFILEUID:9dd6f41ac7904b409591c198d9b922f2

<OFX><SIGNONMSGSRSV1><SONRS><STATUS><CODE>0<SEVERITY>INFO<MESSAGE>Login successful</STATUS><DTSERVER>20160601190228.034[-7:MST]<LANGUAGE>ENG<FI><ORG>AMEX<FID>3101</FI><ORIGIN.ID>FMPWeb<CUSTOMER.TYPE>BCM<START.TIME>20160601190228</SONRS></SIGNONMSGSRSV1></OFX>
'''

ofx = BeautifulSoup(res, 'lxml')
sonrs = ofx.find('sonrs')
code = int(sonrs.find('code').contents[0].strip())
try:
  status = sonrs.find('message').contents[0].strip()
except Exception:
  status = ''
print 'code [{0}], status [{1}]'.format(code, status)
````

Here's my result:
````
$ python /tmp/soup_lxml.py 
code [0], status [Login successful]
````

**Comment by ChromoX** [comment]
Yup that was the problem. I hate having two different versions of Python. Thanks for your help!
