### ISSUE TITLE
wells fargo error

### ISSUE THREAD

**Issue by senorsmile** [captin411/ofxclient#34]
Trying to connect to a Wells Fargo account.  

Getting the following response: 

```
<OFX>
<SIGNONMSGSRSV1><SONRS>
<STATUS>
<CODE>2000
<SEVERITY>ERROR
<MESSAGE>The financial management software you are using is no longer supported. Please upgrade your software or contact us at 1-800-956-4442 for assistance. (2000:9)
</STATUS>
<DTSERVER>20170208195142.478[0:GMT]
<LANGUAGE>ENG
<FI>
<ORG>WF
<FID>3000
</FI>
</SONRS>
</SIGNONMSGSRSV1>
</OFX>
```

**Comment by senorsmile** [comment]
Apparently, there is a setting that can be changed in the generated ini file: 
http://www.ofxhome.com/ofxforum/viewtopic.php?id=47446

However, it never gets that far with the error.  my $HOME/ofxclient.ini is completely blank, so I have no basis to change.  

Is there any way to force it to create the file so I can attempt to tweak things?

**Comment by senorsmile** [comment]
I generated the file manually, using some of the documentation (which happened to be for wells fargo), put in my username and password in plain text, and changed: 

institution.client_args.app_version = 2400

and it works!  Now, the question is, how do I get the username and password to be secured (or change that value initially so the application will do it for me)?

**Comment by captin411** [comment]
I changed the default app_version in the client.py file (see https://github.com/captin411/ofxclient/commit/3c37ef9a3c195ad29a453a9263e8883244871d24).  I am going to presume it works -- if changing that file does not work please let me know.
