### ISSUE TITLE
Citi Credit Cards stopped working

### ISSUE THREAD

**Issue by jhaggard11** [captin411/ofxclient#38]
When trying to download transactions your get the following message in the OFX file:

Access Denied
You don't have permission to access "http://www.accountonline.com/cards/svc/CitiOfxManager.do" on this server.
Reference #18.85ce33b8.1489610984.11a85826 

If I try to readd the Citi Credit Card bank in the OFXclient I get the following error:

authentication failed: 'NoneType' object has no attribute 'find'

Thanks.

**Comment by albaguirre** [comment]
Same here.

**Comment by bdrister** [comment]
This appears to be a common issue, per [ofxhome](http://www.ofxhome.com/ofxforum/viewtopic.php?id=49566). Interestingly, Discover Card also stopped working around the same time with similar circumstances, and ofxhome suggests that [massaging HTTP header order has fixed it](http://www.ofxhome.com/ofxforum/viewtopic.php?id=47793).

**Comment by jhaggard11** [comment]
Cool, bdrister, that does look like my issue.  However, I am not sure how to massage the HTTP header order.  Any clues on where to look on how to do that please?

Thanks.

**Comment by bdrister** [comment]
I don't know the python libraries well enough to know if it's even possible to control this from user code, and I don't have time at the moment to experiment, but if it's possible at all it's probably an edit near ofxclient/client.py line 106, as that has HTTP headers for the request.

**Comment by jhaggard11** [comment]
Thanks, I will.

**Comment by denvaar** [comment]
@captin411 do discover cards still work after the HTTP header re-ordering? I ran into the same problem back in March or so, and was able to get it working by changing the headers, but now after recently trying to pull transaction data from discover's ofx server I am getting an error again. Just wondering if anyone else is seeing this issue

**Comment by jantman** [comment]
@denvaar the HTTP header fix for Discover was released in 2.0.3.

However, on May 10 or 11 a second issue popped up, apparently they changed the ACCTID (account number) values that they are reporting in the OFX. See [my comment here](https://github.com/captin411/ofxclient/issues/40#issuecomment-301346056); no code changes are needed, but you need to either re-run setup, or manually download an OFX statement from their website and get the new account number.

**Comment by jantman** [comment]
I got Citi working. I'm not sure the best way to handle this in code, as I'm using ofxclient from a custom python wrapper, not the CLI or using ``~/ofxclient.ini``.

To get it working, I needed:

* OFX version 102
* APPID QWIN
* APPVER 2400
* __no User-Agent header__, like Discover

The last one seemed to be the clincher.

**Comment by jhaggard11** [comment]
Thanks jantman.

**Comment by jantman** [comment]
This started happening again for me 5 days ago. I'm not sure how to fix it yet...
