### ISSUE TITLE
The Nature of Ofx Clients & Bugs

### ISSUE THREAD

**Issue by sneilan** [captin411/ofxclient#43]
Hey captin411,

I really appreciate your work in this project.

I was wondering, how come banks keep breaking for different settings and versions of ofxclient. Is it just the nature of this protocol? Is it possible to create a truly stable python ofxclient?

I was recently trying to install ofxclient 2.0.3 on a raspberry pi to connect to Chase bank. I have to admit it is very difficult to make this thing work. Once it works however it's great! :)

**Comment by jantman** [comment]
For what it's worth, I don't think this is the nature of the protocol at all. Unfortunately, it seems to be the nature of the banks' virtually-exclusive relationship with Intuit for consumer OFX access. It seems that when Intuit comes out with a new version, many banks change their backends to require that version (even if there are no substantive changes to the OFX protocol or data).

If you look through the forums from other (paid or financially-supported) OFX clients such as Mint, MoneyDance, etc. it seems that even non-Intuit paid services that have relationships with banks have this problem, and have forums full of support responses along the lines of "A new Quicken version was released. We spoke with <financial institution> and we need to update our OFX code to send a new client version."

IMO the bottom line is that consumers using OFX clients other than the biggest proprietary ones are an extreme edge case that banks seem to ignore in a way they'd never ignore an actual standard in the B2B world.

**Comment by sneilan** [comment]
Yeah, that makes sense to me. It may not feasible for someone authoring this as an open source project to have a bank account at every single bank to test this all the time.
