### ISSUE TITLE
Error with Citibank

### ISSUE THREAD

**Issue by jmrgithub** [captin411/ofxclient#77]
I received this error when trying to sync with Citibank tonight:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ledger_autosync-1.0.0-py3.6.egg/ledgerautosync/cli.py", line 92, in sync
    max_days=args.max)
  File "/usr/local/lib/python3.6/dist-packages/ledger_autosync-1.0.0-py3.6.egg/ledgerautosync/sync.py", line 127, in get_new_txns
    (acct.description, ofx.signon.message))
Exception: Error returned from server for Liabilities:Visa: Due to security improvements, connection to this financial software will be shut down on 09/07/2019. Please request your financial management software contact Citi at citiOFXmigration@citi.com.

Any suggestions on how to fix?

Thanks.

**Comment by Greg117** [comment]
I am not sure if it's new or not.  However, on the Citi website under Profile-More Settings ->Security->Manage Desktop Apps.

If you go there, it allows 10 minutes to "Log in" from 3rd party software applications.  I tried sending an account list request as well as a transaction request and I'm getting the same error.  I am not sure if this feature is new today or not.  However, I'm currently stuck where you are as well.
```xml
<OFX>
  <SIGNONMSGSRSV1>
    <SONRS>
      <STATUS>
        <CODE>2000
        <SEVERITY>ERROR
        <MESSAGE>Due to security improvements, connection to this financial software will be shut down on 09/07/2019. Please request your financial management software contact Citi at citiOFXmigration@citi.com.
      </STATUS>
      <DTSERVER>20190902
      <USERI<LANGUAGE>ENG
      <FI>
        <ORG>Citigroup
        <FID>24909
      </FI>
      <INTU.BID>4894
      <INTU.USERID>******
    </SONRS>
  </SIGNONMSGSRSV1>
</OFX>
```

**Comment by captin411** [comment]
Im not an expert on the ins and outs of particular financial institution policies or technology changes.

I do know that the OFX specification is quite old and, I speculate, banks will slowly be moving away from that spec over time to support increasing security needs like 2FA, biometric standards etc

Perhaps try teaching out to your financial institution and see if OFX is being completely phased out.

If you find its phased out and are looking for integration tooling for transaction downloads, try googling for “financial aggregation apis” or “financial data aggregation” and you might find some suitable replacements out there.

Best of luck!

**Comment by Greg117** [comment]
For me, collections have started working again.  I'm wondering if they are making server changes and it was just a hiccup.

**Comment by jmrgithub** [comment]
It's working for me again too, so I'm closing this issue.  

I just hope things don't change after Sept. 7.
